<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('devices', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            // Generated by the handset and stable across reinstalls of the same
            // app data, so a device that restores a backup is still one device.
            $table->char('uuid', 36)->unique();
            $table->string('name');
            $table->string('platform', 32)->default('android');
            $table->string('app_version', 32)->nullable();
            // The high-water mark this device has already pulled. Kept server
            // side as well as on the handset so a reinstalled app can resume.
            $table->timestamp('last_pulled_at')->nullable();
            $table->timestamp('last_pushed_at')->nullable();
            $table->timestamp('last_seen_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'last_seen_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('devices');
    }
};
